baseurl = "http://whurley.com/"
languageCode = "en-us"
title = "Whurley"
theme = "whurley"

[[menu.main]]
  Name = "digital citizen"
  Title = "digital citizen"
  URL = "/#digital-citizen"
[[menu.main]]
  Name = "speaker + author"
  Title = "speaker + author"
  URL = "/#speaker-author"
[[menu.main]]
  Name = "entrepreneur + innovator"
  Title = "entrepreneur + innovator"
  URL = "/#entrepreneur-innovator"



[[menu.social]]
  Name = "Facebook"
  Identifier = "fa-facebook"
  URL = "https://www.facebook.com/whurley/"
  weight = 1
[[menu.social]]
  Name = "Twitter"
  Identifier = "fa-twitter"
  URL = "https://twitter.com/whurley"
  weight = 2
[[menu.social]]
  Name = "Wikipedia"
  Identifier = "fa-wikipedia-w"
  URL = "https://en.wikipedia.org/wiki/Whurley"
  weight = 3
[[menu.social]]
  Name = "Vimeo"
  Identifier = "fa-vimeo"
  URL = "https://vimeo.com/whurley"
  weight = 4



[[menu.footer]]
  name = "Press:"
  weight = 1
  identifier = "press"
[[menu.footer]]
  name = "Link"
  url = "/link/"
  parent = "press"
[[menu.footer]]
  name = "Link"
  url = "/link/"
  parent = "press"
[[menu.footer]]
  name = "Link"
  url = "/link/"
  parent = "press"
[[menu.footer]]
  name = "Link"
  url = "/link/"
  parent = "press"

[[menu.footer]]
  weight = 2
  name = "About:"
  url = "/about/"
  identifier = "about"
[[menu.footer]]
  name = "Wikipedia"
  url = "/Wikipedia/"
  parent = "about"
[[menu.footer]]
  name = "Biography"
  url = "/Biography/"
  parent = "about"
[[menu.footer]]
  name = "Head Shot"
  url = "/Head Shot/"
  parent = "about"

[[menu.footer]]
  weight = 3
  name = "Social:"
  url = "/social/"
  identifier = "social"
[[menu.footer]]
  name = "Twitter"
  url = "https://twitter.com/whurley"
  parent = "social"
[[menu.footer]]
  name = "Facebook"
  url = "https://www.facebook.com/whurley/"
  parent = "social"
[[menu.footer]]
  name = "LinkedIn"
  url = "https://www.linkedin.com/in/whurley"
  parent = "social"
[[menu.footer]]
  Name = "Wikipedia"
  URL = "https://en.wikipedia.org/wiki/Whurley"
  parent = "social"
[[menu.footer]]
  Name = "Vimeo"
  URL = "https://vimeo.com/whurley"
  parent = "social"

[[menu.footer]]
  weight = 4
  name = "Patents:"
  url = "/patents/"
  identifier = "patents"
[[menu.footer]]
  name = "US 6,757,724"
  url = "/US 6,757,724/"
  parent = "patents"
[[menu.footer]]
  name = "US 6,704,797"
  url = "/US 6,704,797/"
  parent = "patents"

[[menu.footer]]
  weight = 5
  name = "Experience:"
  url = "/experience/"
  identifier = "experience"
[[menu.footer]]
  name = "Apple"
  url = "/Apple/"
  parent = "experience"
[[menu.footer]]
  name = "IBM"
  url = "/IBM/"
  parent = "experience"
[[menu.footer]]
  name = "Chaotic Moon"
  url = "/Chaotic Moon/"
  parent = "experience"
[[menu.footer]]
  name = "Honest Dollar"
  url = "/Honest Dollar/"
  parent = "experience"
[[menu.footer]]
  name = "Goldman Sachs"
  url = "/Goldman Sachs/"
  parent = "experience"

[[menu.footer]]
  weight = 6
  name = "Projects:"
  url = "/projects/"
  identifier = "projects"
[[menu.footer]]
  name = "NonProfit"
  url = "/NonProfit/"
  parent = "projects"
[[menu.footer]]
  name = "Charity"
  url = "/Charity/"
  parent = "projects"